### ISSUE TITLE
Os Error

### ISSUE THREAD

**Issue by kisnami** [haf-decent/arpping#1]
im using windows os, when i start a js file its shows an error like 'ifconfig' its not a recongize commend
![capture](https://user-images.githubusercontent.com/33775177/51196706-bac52280-1915-11e9-8253-afe6d4bf89b7.PNG)

**Comment by haf-decent** [comment]
Hey,

To be honest, I didn’t have a chance to test the package on Windows, so it seems the commands didn’t quite translate properly. I think the Windows equivalent is ‘ipconfig’ instead of ‘ifconfig’. Would you mind changing that and testing to see if that at least fixes that part?

- Ryan

**Comment by haf-decent** [comment]
I've since resolved this issue using os-specific commands/flags. Also, I just published v1.0.0 which restructures things to hopefully make this module easier to use on all devices, so check that out if you're still interested in using this package.
