### ISSUE TITLE
No Wifi Connection

### ISSUE THREAD

**Issue by Craigzyc** [haf-decent/arpping#10]
It seems this doesn't support a system that doesn't have wifi. Why not support ethernet only devices?

**Comment by haf-decent** [comment]
Hey @Craigzyc, that's a good question. I created this for a wireless automation project I was working on which didn't include ethernet-connected devices, so I didn't think to make sure it worked in that case. I'll make some time over the next week or so to see if I can't get it working. Thanks for the feedback

**Comment by haf-decent** [comment]
@Craigzyc I actually had some time just now to look into it and it seems like the `os` module actually has a pretty helpful method called `networkInterfaces` that lists out all interface connections. I created a new branch called `interfaces` with that change - seems to work properly on my machine, so if you could pull that down and test to make sure it works on yours, I'll merge it in.
