### ISSUE TITLE
Error ping to valid ip (and alive)

### ISSUE THREAD

**Issue by ljgazzano** [haf-decent/arpping#5]
Hi. When I ping from the same server using this library, the result is null. But if I do a traditional ping, it works. any ideas?

![image](https://user-images.githubusercontent.com/19694431/86066644-1ff8cf00-ba49-11ea-80e7-72ccf073d9c2.png)

**Comment by haf-decent** [comment]
Hey, so from what I can see in your screenshot, it looks like you're using the `arp` command. If you use the `arp` command directly in terminal, you'll see similar behavior where it doesn't necessarily find all devices on your network. You can check out [this link](https://superuser.com/questions/874097/arp-a-command-not-working-doesnt-list-devices) for a short explanation - basically, your device keeps a dynamic ARP mapping and that mapping expires for each device after a few minutes of inactivity between your device and the target device, which prevents `arp` from finding that device when called. 

From my understanding, a good way to address this limitation (and the way it is implemented in `arpping.discover`) is to `ping` every ip address on a network before using `arp`. This way, you refresh the dynamic ARP mapping by sending packets to every device.

Having said all that, the `arp` command is mostly just useful for finding mac addresses, so if you don't need that information, I would suggest simply using `arpping.ping` (if that's not what you're doing already) and see if that gives you the results you're looking for.
